version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
# docker-compose -f docker-compose.dev.yml up
# docker-compose -f docker-compose.dev.yml up -d run in background
# docker-compose -f docker-compose.dev.yml down --volumes to ensure that nothing is left and start from a clean slate
