services:
  app:
    image: todo-frontend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    container_name: todo-frontend-dev # This will name the container todo-frontend-dev

# docker-compose -f docker-compose.dev.yml up
# docker-compose -f docker-compose.dev.yml up -d              run in background
# docker-compose -f docker-compose.dev.yml down --volumes     to ensure that nothing is left and start from a clean slate
