version: '3.8'
# docker-compose -f docker-compose.dev.yml --env-file ./server/.env up
# docker-compose -f docker-compose.dev.yml --env-file ./server/.env config
services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
  client:
    image: bloglist-client-dev
    build:
      context: ./client/
      dockerfile: dev.Dockerfile
    volumes:
      - ./client/:/usr/src/app
    ports:
      - 3000:3000
  server:
    image: bloglist-server-dev
    build:
      context: ./server/
      dockerfile: dev.Dockerfile
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3003:3003
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - TEST_MONGODB_URI=${TEST_MONGODB_URI}
      - PORT=3003
      - SECRET=${SECRET}
