name: 11-1 Pokedex Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    defaults:
      run:
        working-directory: part11/11-1-pokedex
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: test
        run: npm run test
