name: 11-1 Pokedex Deployment Pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  build:
    defaults:
      run:
        working-directory: part11/11-1-pokedex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: part11/11-1-pokedex
          command: npm run test:e2e
          start: npm run start:full
          wait-on: 'http://localhost:5000/'
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy to heroku
        if: ${{ github.event_name == 'push', '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'fullstackopen-11-1-pokedex' #Must be unique in Heroku
          heroku_email: 'chendrix1123@gmail.com'
          appdir: 'part11/11-1-pokedex'
          healthcheck: 'https://fullstackopen-11-1-pokedex.herokuapp.com/health'
          rollbackonhealthcheckfailed: true
      - name: bump version
        if: ${{ github.event_name == 'push', '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
